{% set name = "glum" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0354f792a1467ae295b9f9ec9fe2fb1b4af9ee97c0f72cb5ef2cf785c0cca792


build:
  number: 0
  skip: true  # [py<39]
  skip: true  # [python_impl == "pypy"]
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - GLM_ARCHITECTURE=default


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - python
    - cython
    - llvm-openmp  # [osx]
    - numpy
    - pip
    - scikit-learn >=0.23
    - setuptools
    - setuptools_scm
  run:
    - python
    - formulaic >=0.6
    - joblib
    - numexpr
    - packaging
    - pandas
    - scikit-learn >=0.23
    - scipy
    - tabmat >=4.0.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - glum

about:
  home: https://github.com/Quantco/glum
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'High performance Python GLMs with all the features! '
  description: |
    glum is a fast and feature-complete GLM estimator. It supports built-in
    cross-validation, exploiting regularization path, L1 and L2 regularization
    with Tikhonov penalties, sample weights, offsets, linear inequality constraints,
    and more!
  doc_url: https://glum.readthedocs.io/
  dev_url: https://github.com/Quantco/glum

extra:
  recipe-maintainers:
    - MatthiasSchmidtblaicherQC
    - MarcAntoineSchmidtQC
    - xhochy
    - tbenthompson
    - janjagusch
    - jtilly
