{% set name = "glum" %}
{% set version = "3.0.0a2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 58879c63af50a0f3de8da168f4b12db4cf4019e60d7473590208ff4d6b35a0a0


build:
  number: 0
  skip: true # [py<39]
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - GLM_ARCHITECTURE=default


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - python
    - cython
    - llvm-openmp  # [osx]
    - numpy
    - pip
    - scikit-learn >=0.23
    - setuptools_scm
  run:
    - python
    - joblib
    - numexpr
    - {{ pin_compatible('numpy') }}
    - pandas
    - scikit-learn >=0.23
    - scipy
    - tabmat >=4.0.0a1
    - formulaic >=0.4

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - glum

about:
  home: https://github.com/Quantco/glum
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'High performance Python GLMs with all the features! '
  description: |
    glum is a fast and feature-complete GLM estimator. It supports built-in
    cross-validation, exploiting regularization path, L1 and L2 regularization
    with Tikhonov penalties, sample weights, offsets, linear inequality constraints,
    and more!
  doc_url: https://glum.readthedocs.io/
  dev_url: https://github.com/Quantco/glum

extra:
  recipe-maintainers:
    - MarcAntoineSchmidtQC
    - xhochy
    - tbenthompson
    - janjagusch
    - jtilly
