context:
  name: glum
  version: "3.1.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 76613250d4c3c66b408e0cc972081ee593b29d9c406ba8097f61969160ee44d4


build:
  number: 0
  skip: python_impl == "pypy"
  script:
    content: python -m pip install . -vv
    env:
      GLM_ARCHITECTURE: default

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython
        - numpy
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - ${{ compiler("cxx") }}
    - if: osx
      then:
        - llvm-openmp
    - if: linux
      then:
        - libgomp
  host:
    - python
    - cython
    - if: osx
      then:
        - llvm-openmp
    - numpy
    - pip
    - scikit-learn >=0.23
    - setuptools
    - setuptools-scm
  run:
    - python
    - formulaic >=0.6
    - joblib
    - numexpr
    - packaging
    - pandas
    - scikit-learn >=0.23
    - scipy
    - tabmat >=4.0.0

tests:
  - python:
      pip_check: true
      imports:
        - glum

about:
  homepage: https://github.com/quantco/glum
  license: BSD-3-Clause
  license_file: LICENSE
  summary: High performance Python GLMs with all the features!
  description: |
    glum is a fast and feature-complete GLM estimator. It supports built-in
    cross-validation, exploiting regularization path, L1 and L2 regularization
    with Tikhonov penalties, sample weights, offsets, linear inequality constraints,
    and more!
  documentation: https://glum.readthedocs.io
  repository: https://github.com/quantco/glum

extra:
  recipe-maintainers:
    - MatthiasSchmidtblaicherQC
    - MarcAntoineSchmidtQC
    - xhochy
    - stanmart
    - janjagusch
    - jtilly
